### ISSUE TITLE
Interesting / Catchy Name

### ISSUE THREAD

**Issue by dreid93** [Glavin001/TorrentAutomator#13]
@Glavin001 please feel free to dismiss this issue. I was hoping we could brainstorm a more interesting name. 

Potentials : 

- AuTorBot (pronounced Aw-Tor-Bot like Autobot)
- TxTor (pronounced Text-Tor)

**Comment by Glavin001** [comment]
I am going to be branching out TorrentAutomator into a Virtual Assistant for Home Media, including complex searching for TV shows and movies, downloading them with your favourite client, and even managing your media library and providing recommendations in the future. There will be an API (already implemented) and Web, iOS -- and possibly Android -- clients (coming next), with speech recognition and natural language commands.

The obvious and simple name could be: MediaAssistant :stuck_out_tongue_winking_eye: 

I would really like to give this project a personable name, like Jarvis, Siri, Jasper, etc..

Thoughts? :smiley:

**Comment by Glavin001** [comment]
I think I have settled on `Donna`.

![Donna3](http://media.tumblr.com/tumblr_m5nqzwKwNe1r4l7pjo2_500.gif)
![Donna2](http://38.media.tumblr.com/06631ca9f96a3ff7e32d82d00f5eec33/tumblr_nkjwzjb93j1sryheco1_500.gif)
![Donna1](http://pbs.twimg.com/media/BASFEtUCIAMDZFt.jpg:large)

**Comment by dreid93** [comment]
:+1: this made me laugh good sir!
