### ISSUE TITLE
Optimize Dockerfile

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/TorrentAutomator#32]
- Speeding up `npm install` in docker: https://github.com/npm/npm/issues/8836
- Building Efficient Dockerfiles - Node.js: http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/
- Dockerfile best practices: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/
- Resin.io Build Optimization: http://docs.resin.io/#/pages/deployment/build-optimisation.md
- Gotchas in Writing Dockerfile: http://kimh.github.io/blog/en/docker/gotchas-in-writing-dockerfile-en/
- Docker Explained: Using Dockerfiles to Automate Building of Images: https://www.digitalocean.com/community/tutorials/docker-explained-using-dockerfiles-to-automate-building-of-images

**Comment by Glavin001** [comment]
Got it down to under a minute!

**Comment by devotox** [comment]
have you heard of docker-osx-dev ... this has been the only way i have found to even tolerate using docker on a mac. It actually seems almost fully native. nothing more than 500ms difference at most

**Comment by Glavin001** [comment]
No I haven't. Is https://github.com/brikis98/docker-osx-dev it? Thanks for the recommendation. I'll take a look.
The Dockerfile currently is only for a Resin.io installation, however I want to make installation as easy as possible and Docker is working well so far.

**Comment by devotox** [comment]
Yes thats the one ... works very well
