### ISSUE TITLE
[Solved]Add torrent problem

### ISSUE THREAD

**Issue by AzSiAz** [Glavin001/TorrentAutomator#34]
Hi, 
I got a little problem after fresh start to add torrent by webui, error is : 
`create {} { query: {} }`
`Error: Missing Torrent URL field.`

EDIT : After I post and check your code I found the problem on app/scripts/main.js
line 15 : `url: torrent.torrentLink` instead of : `url: torrent.torrentUrl`
Well thanks for this api useable with twilio, I think I will get a closer look :D

**Comment by Glavin001** [comment]
Please submit a Pull Request with anything you fixed! Thank you!
